Slack connector
CLIP-HPC/goslmailer pull request #25
Opened 2023-01-20 16:20 UTC by cecilialau6776

Slack connector using Slack api.

2023-01-23 11:20 UTC, pja237 commented on cmd/gobler/gobler.go
> +	// cfg.DumpConfig(l)
So you've removed the dumpconfig altogether to take care of #23 ?

2023-01-23 11:21 UTC, pja237 commented on cmd/gobler/gobler.toml
> +# Unlimited if this is set to 0.
Great, love this 👍

2023-01-23 11:22 UTC, pja237 commented on connectors/slack/slack.go
> +		return errors.New("discord bot token must be defined, aborting")
could be slack token, to avoid confusion 😄

2023-01-23 11:28 UTC, pja237 commented on connectors/slack/slack.go
> +		// If a user just uses --mail-user=slack:user:[channelid] they bypass the check done if they use slack:channel:[channelid].
This part of code i can't comment on since i don't know how slack works regarding bots, channels and users, so i'll just trust you've tested this and it's all good.

Only thing that i would ask of you is to document this in the appropriate README sections:

https://github.com/CLIP-HPC/goslmailer/blob/f8118e6997edf6f5da11a7dc554890e15501f642/README.md?plain=1#L40-L45
https://github.com/CLIP-HPC/goslmailer/blob/f8118e6997edf6f5da11a7dc554890e15501f642/README.md?plain=1#L75-L81
https://github.com/CLIP-HPC/goslmailer/blob/f8118e6997edf6f5da11a7dc554890e15501f642/README.md?plain=1#L209-L217

And add a section describing the usage of slack connector please.

2023-01-23 11:32 UTC, pja237 reviewed
Thank you so much for the effort and this great PR.
Can't really comment on the workflow part for the slack connector regarding messages to users vs channels and the API, since i'm not familiar with slack.
Please document this part for my understanding (and completeness) in the README and perhaps @timeu can add his comments on this topic.

2023-01-24 13:45 UTC, timeu requested changes
From my point of view it looks good. thanks for the contribution. 
I would still like to see the new slack connected documented preferably with some screenshots as it is done for the other ones.

2023-01-24 16:49 UTC, cecilialau6776 commented
Thank you so much for all the comments! I'm working on the changes and will resolve comments as I push changes.

2023-01-26 18:16 UTC, cecilialau6776 commented on cmd/gobler/gobler.go
> +	// cfg.DumpConfig(l)
I think a better solution would be to add a debug flag/config/command line param and only dump the config if it's true.

2023-01-28 02:17 UTC, cecilialau6776 commented on connectors/slack/slack.go
> +		// If a user just uses --mail-user=slack:user:[channelid] they bypass the check done if they use slack:channel:[channelid].
I believe I've updated the appropriate documentation. Please let me know if you think anything should be more thoroughly documented.

2023-01-30 13:57 UTC, cecilialau6776 commented
I believe I've updated the appropriate documentation. Please let me know if you think anything should be more thoroughly documented.

2023-01-30 14:05 UTC, timeu approved these changes

2023-01-30 14:05 UTC, timeu commented
@cecilialau6776 : Thanks for the changes. Let's wait until  @pja237 had a change to look over it and then we will merge it.

2023-02-08 08:41 UTC, pja237 commented on cmd/gobler/gobler.go
> +	// cfg.DumpConfig(l)
I agree, lets do a separate issue for this, for now it's perfectly fine to stay commented.

2023-02-08 08:44 UTC, pja237 approved these changes
Looks great now. Thanks again for your patience everyone, lets get this merged and released, then i'll see about #24.
@cecilialau6776 would you please just open a separate issue to do the dumping of config via flag/config/cmdline so we don't forget about it.

2023-02-08 08:46 UTC, merged